name: Build All Platforms

on:
  push:
  pull_request:

jobs:
  linux:
    name: Linux (GCC)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential nasm
      - name: Setup dependencies
        run: git submodule update --init
      - name: Build
        run: sudo make prod-all

  emcc:
    name: Linux (Emscripten)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 1.38.40
          actions-cache-folder: 'emsdk-cache'
      - name: Verify emcc install
        run: emcc -v
      - name: Setup dependencies
        run: git submodule update --init
      - name: Build
        run: sudo make prod-all TARGET=wasm

  windows:
    name: Windows (MSVC)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (MSYS2)
        uses: msys2/setup-msys2@v2
        with:
          install: base-devel mingw-w64-x86_64-gcc mingw-w64-x86_64-nasm git
          msystem: MINGW64

      - name: Build with MSYS2 Make
        shell: msys2 {0}
        run: git submodule update --init && make prod-all TARGET=win32

